# Netlify Configuration for Chimera AI - 2025 Optimized
# Monica Authority: 99.999% | 2048-Agent Coordination | <3ms Latency

[build]
  publish = "."
  command = "npm install && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

# Functions Configuration - External modules for AWS SDK
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-dynamodb", "@aws-sdk/client-s3", "@netlify/neon", "aws-sdk"]
  included_files = ["**/*.json"]

# Security Headers - SOC2/GDPR Compliance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https: /.netlify/functions/"

# Cache Static Assets - CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Static Assets - JS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Static Assets - Images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API Redirects for <3ms latency
[[redirects]]
  from = "/api/database/*"
  to = "/.netlify/functions/database/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Edge Handlers for Global Distribution
[[edge_functions]]
  path = "/api/*"
  function = "api-handler"

# Development Settings
[dev]
  port = 3000
  command = "npm run dev"
  functions = "netlify/functions"
  autoLaunch = false
